### PR TITLE
Window scaling

### LINKED ISSUE #104: Scale the window
I want to be able to scale the SF2 window and have the UI scale with it.

At minimum, this will be a configuration option to set the physical size of the window. The logical size of SF2 will remain at 1280x720, but the pixels will scale with the window size.

### PR DESCRIPTION
**Pull request by micheldebree**
Added a config option to scale the contents of the window.

Fixes #104 ~~once we explain how change config~~

### CODE REVIEW

**Comment by micheldebree** [comment]
If I use a factor 1.3, there is a small flickering red line on the right border

**Comment by micheldebree** [comment]
Thomas: 
> I think we should allow scaling in 25% increments of the original size in the range of 50 to 200%

**Review by TheRealLaxity — APPROVED** [review]
Good stuff!

**Comment by micheldebree** [comment]
> If I use a factor 1.3, there is a small flickering red line on the right border

If I go from 0.5 to 2.0 with 0.1 steps, 1.3 is the only value that causes this... if we can fix that, we can allow finer grained 0.1 steps

**Comment by micheldebree** [comment]
I think we've stumbled upon this bug in SDL: https://github.com/libsdl-org/SDL/issues/1164

I am tempted to not try and work around it and just document in the config that the user can try another value if the line appears. Blame SDL if neccesary.

**Pull request merged**
